# Data Analysis
Numpy: is a python extension for large, multi dimensional arrays and matrices along with a large library of high-level mathmateical functions.

In [54]:
x = 20

In [70]:
import sys
print(sys.getsizeof(x))
print(x.bit_length())

28
5


In [72]:
import sys
l = [2, 3, 4, 5]
print(l)
print(l[0])
print(sys.getsizeof(l))
print(sys.getsizeof(l[0]))

[2, 3, 4, 5]
2
96
28


In [74]:
from array import array

a = array('H', [2, 3, 4, 5])   # H is a type code which determines the type of the array. H --> unsigned short int

print(a)
print(a[0])
print(sys.getsizeof(a))
print(sys.getsizeof(a[0]))

array('H', [2, 3, 4, 5])
2
72
28


In [78]:
import numpy as np

In [79]:
a = np.array([2, 3, 4, 5, 7])

In [80]:
a

array([2, 3, 4, 5, 7])

In [81]:
a.shape

(5,)

In [82]:
a.dtype, a.nbytes

(dtype('int32'), 20)

In [83]:
a.ndim

1

In [84]:
a.size

5

In [85]:
a = np.array([2+3j, 4+5j])
a.dtype, a.nbytes

(dtype('complex128'), 32)

In [86]:
a = np.array([True, False, True])
a.dtype, a.nbytes

(dtype('bool'), 3)

In [87]:
a = np.array(['Apple', 'Banana', 'Mango'])
a.dtype, a.nbytes

(dtype('<U6'), 72)

In [91]:
a = np.array(range(10))

In [92]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a = np.array(range(10), dtype=float)

In [94]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
a.dtype

dtype('float64')

In [96]:
a = np.array([True, False, True])
a.dtype, a.nbytes

(dtype('bool'), 3)

In [97]:
a = np.array(['Apple', 'Mango', 'Banana'], dtype='U10')
a.dtype, a.nbytes

(dtype('<U10'), 120)

In [120]:
# multi dimension arrays:
l = [2, 3, 4]
l1 = [[[2, 3, 4],
      [4, 5, 6]],
    [[2, 3, 4],
    [4, 5, 6]],
    [[2, 3, 4],
    [4, 5, 6]]
    ]

a = np.array(l1)
print(a.shape, a.ndim)

(3, 2, 3) 3


In [124]:
# data types:
# bool: Boolean (True or False) stored as a bit.
# inti: Platform integer (normally either int32 or int64).
# int8: Byte (-128 to 127).
# int16: Integer (-32768 to 32767).
# int32: Integer (-2 31 to 2 31 -1).
# int64: Integer (-2 63 to 2 63 -1).
# uint8: Unsigned integer (0 to 255).
# uint16: Unsigned integer (0 to 65535).
# uint32: Unsigned integer (0 to 2 ** 32 - 1).
# uint64: Unsigned integer (0 to 2 ** 64 - 1).
# float16: Half precision float: sign bit, 5 bits exponent, and 10 bits mantissa.
# float32: Single precision float: sign bit, 8 bits exponent, and 23 bits mantissa. 
# float64 or float: Double precision float: sign bit, 11 bits exponent, and 52 bits mantissa.
# complex64 Complex number, represented by two 32-bit floats (real and imaginary components).
# complex128 or complex: Complex number, represented by two 64-bit floats (real and imaginary components).
# SN: String with N characters,i.e, 'S20', means string with width 20 characters.

In [125]:
# dtype Character codes:
# Type code C Type Minimum size in bytes 
# 'b' signed integer 1 
# 'B' unsigned integer 1 
# 'u' Unicode character 2 (see note)
# 'h' signed integer 2 
# 'H' unsigned integer 2 
# 'i' signed integer 2 
# 'I' unsigned integer 2 
# 'l' signed integer 4 
# 'L' unsigned integer 4 
# 'q' signed integer 8 (see note)
# 'Q' unsigned integer 8 (see note) 
# 'f' floating point 4 
# 'd' floating point 8

In [ ]:
a = np.array(range(1, 11, 3))

In [100]:
# arange()

a = np.arange(1, 11, 3)
a

array([ 1,  4,  7, 10])

In [102]:
# empty()

a = np.empty(4)
print(a.dtype)
print(a)

float64
[2. 3. 4. 5.]


In [103]:
a = np.empty((4, 3, 2))
print(a.dtype)
print(a)

float64
[[[0. 1.]
  [1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 1.]
  [1. 1.]
  [0. 0.]]

 [[0. 1.]
  [1. 1.]
  [0. 0.]]]


In [106]:
a = np.zeros((3, 5), dtype='uint64')
print(a.dtype)
print(a)

uint64
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [107]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [108]:
a = np.ones((4, 3, 2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [109]:
a = np.arange(1, 25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [110]:
a.reshape(4, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [111]:
a.reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [114]:
# modify actual array

a.resize(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [115]:
a = np.arange(24).reshape(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [116]:
# take a copy of the array

a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [117]:
# produce view of the array

b = a.ravel()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [118]:
# traversing array using ravel:

for x in a.ravel():
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [126]:
# Note: The difference is that flatten always returns a copy and ravel returns a view of the original array whnever possible.
# This isn't visible in the printed output, but if you modify the array returned by ravel, it may modify the entries in the
# original array. If you modify the entries in an array returned from flatten this will never happen. ravel will often be
# faster since no memory is copied, but you have to be more careful about modifying the array it returns.

In [128]:
a = np.arange(24).reshape(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [129]:
a[1, 4] = 999
a

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9, 999,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [130]:
a[1, :4] = 999
a

array([[  0,   1,   2,   3,   4,   5],
       [999, 999, 999, 999, 999,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [131]:
# applying math function
c = np.sin(a)
c

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427],
       [-0.02646075, -0.02646075, -0.02646075, -0.02646075, -0.02646075,
        -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784, -0.28790332,
        -0.96139749],
       [-0.75098725,  0.14987721,  0.91294525,  0.83665564, -0.00885131,
        -0.8462204 ]])

In [132]:
c < 0

array([[False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False, False, False,  True,  True],
       [ True, False, False, False,  True,  True]])

In [133]:
c[c < 0] = 0
c

array([[0.        , 0.84147098, 0.90929743, 0.14112001, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.42016704, 0.99060736, 0.65028784, 0.        ,
        0.        ],
       [0.        , 0.14987721, 0.91294525, 0.83665564, 0.        ,
        0.        ]])

In [134]:
c[c > 0] = 1
c

array([[0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 0., 0.]])

In [135]:
np.random.rand(10)

array([0.62200991, 0.07042899, 0.35819368, 0.34739866, 0.20517357,
       0.00860684, 0.99245236, 0.24412592, 0.09728202, 0.28095107])

In [136]:
np.linspace(1, 100,15)

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])

In [137]:
l = [[[2, 3, 4],
     [4, 5, 6]],
     [[2, 3, 4],
     [4, 5, 6]],
     [[2, 3, 4],
     [4, 5, 6]]
    ]
a = np.array(l)
a.shape

(3, 2, 3)

In [138]:
l[2][1][1]

5

In [139]:
# Broadcasting Rules:
# In order for an operation to broadcast, the size of all the trailing dimension for both arrays must either be equal
# OR one of them must be one:

#   A(1d array): 3
#   B(2d array): 2 x 3
#   Result(2d array): 2 x 3

#   A(2d array): 6 x 1
#   B(3d array): 1 x 6 x 4
#   Result (3d array): 1 x 6 x 4

#   A(4d array): 3 x 1 x 6 x 1
#   B(3d array): 2 x 1 x 4
#   Result (4d array): 3 x 2 x 6 x 4

In [140]:
# np.linspace() dides the range into n equal partitions and returns list of points.
np.linspace(1, 100, 15)

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])